version: '3.8'

services:
  app:
    container_name: hoonflearn_server
    build:
      context: .
      dockerfile: Dockerfile
      # 개발 환경
      target: development
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # 컨테이너 내부의 node_modules 보호
    # 개발 환경에서만
    command: yarn start:dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: hoonflearn_db
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres:
