version: '3.8'

services:
  app:
    container_name: hoonflearn_server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.prod

    ports:
      - 8080:8080
    restart: always

  redis:
    container_name: hoonflearn_redis
    image: redis
    ports:
      - 6379:6379
    env_file: .env
    volumes:
      - ./redis/data:/data
