version: '3.8'

services:
  app:
    container_name: hoonflearn_server
    build:
      context: .
      dockerfile: Dockerfile
      # 개발 환경
      target: development
    env_file: .env
    volumes:
      - .:/usr/src/app # 호스트와 컨테이너의 파일 공유 - 핫 리로딩을 위해서(개발 단계)
      - /usr/src/app/node_modules # 호스트와 컨테이너 node_modules 격리(운영체제나 환경이 다를 수 있으므로)
    # 개발 환경에서만
    command: yarn start:dev
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: hoonflearn_db
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    container_name: hoonflearn_redis
    image: redis
    ports:
      - 6379:6379
    env_file: .env
    volumes:
      - ./redis/data:/data
# volumes:
#   postgres:
